### ISSUE TITLE
Traverse Non-Parameterized Superclasses not supported

### ISSUE THREAD

**Issue by matteozanon** [instancio/instancio#790] opened 2023-10-26 12:18 UTC
**Describe the bug**
In the current implementation of `createSuperclassTypeMap` method within the `TypeHelper` class, the method ceases traversal through the class hierarchy if a non-parameterized type is encountered. However, this approach can miss generic type information in ancestors if a child class does not have generics but its ancestors do. This is evident in the following class hierarchy scenario:

```java
class A<T> {
    private T name;
}

class B extends A<String> {}

class C extends B {}
```
When using Instancio on class C, the field `name` in the example won't be instantiated due to the missing traversal to the generic type defined in class A.

**Proposed Solution**
A modification to the `createSuperclassTypeMap` to continue traversal through superclasses even if they are not `ParameterizedType` will resolve this issue. Below is the proposed solution:

```java
Map<Type, Type> createSuperclassTypeMap(final Class<?> targetClass) {
    Map<Type, Type> resultTypeMap = new HashMap<>();

    traverseHierarchy(targetClass, resultTypeMap);

    if (resultTypeMap.isEmpty()) {
        return Collections.emptyMap();
    }

    LOG.trace("Created superclass type map: {}", resultTypeMap);
    return resultTypeMap;
}

private void traverseHierarchy(Class<?> clazz, Map<Type, Type> resultTypeMap) {
    if (clazz == null || Object.class.equals(clazz)) {
        return;
    }

    Type supertype = clazz.getGenericSuperclass();
    if (supertype instanceof ParameterizedType) {
        addTypeParameters((ParameterizedType) supertype, resultTypeMap);
    }

    traverseHierarchy(TypeUtils.getRawType(supertype), resultTypeMap);
}
```

- Java version: 17
- Instancio version: 3.4

**Comment by armandino** [comment] 2023-10-26 14:26
@matteozanon - thanks for raising the bug! I tried to reproduce it using the following sample but it seems to work:

https://github.com/instancio/instancio-github-issues/tree/main/issue-790

I guess I am missing something. Would you mind providing a reproducible example here or by forking the above repo?

**Comment by matteozanon** [comment] 2023-10-26 14:45
Hi @armandino, you are right, the scenario having the issue is the following. Sorry for the wrong input.

```java
class A<T> {
    private T name;
}

class B<T> extends A<T> {}

class C extends B<String> {}

class D extends C {}

D bean = Instancio.of(D.class).create();
assertNotNull(nonDirect.getName());
```

**Comment by armandino** [comment] 2023-10-26 15:04
Awesome, thank you. I could reproduce the issue using your example. Since you already have a proposed fix, let me know if you're interested in submitting a PR.

**Comment by matteozanon** [comment] 2023-10-26 16:07
PR created

**Comment by armandino** [comment] 2023-10-26 16:37
@matteozanon thank you! Merged. I'll push a new version out tonight.

**Closed by armandino** 2023-10-26 16:37 UTC
Labels: type: bug

**Comment by armandino** [comment] 2023-10-27 03:44
@matteozanon version `3.4.1` should be available from Maven central. Let me know if you run into any other issues.
