### ISSUE TITLE
UnusedSelectorException in Spring Application

### ISSUE THREAD

**Issue by dominik42** [instancio/instancio#637] opened 2023-06-13 19:55 UTC
**Describe the bug**
While in raw tests, Instancio works properly, there are an error if used within a Spring Service within a Vaadin application.

**Expected result**
The pojo is created according the given instancio expressions.

**Actual result**
The following error occured:
`org.instancio.exception.UnusedSelectorException: 
Found unused selectors referenced in the following methods:

 -> Unused selectors in generate(), set(), or supply():
 1: field(Pruefauftrag, "createdAt")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:41)
 2: field(Pruefauftrag, "createdBy")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:42)
 3: field(Pruefauftrag, "id")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:39)
 4: field(Pruefauftrag, "modifiedAt")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:43)
 5: field(Pruefauftrag, "modifiedBy")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:44)
 6: field(Pruefauftrag, "nummer")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:40)

This error aims to highlight potential problems and help maintain clean test code.

Possible causes:

 -> Selector did not match any field or class within this object.
 -> Selector target is beyond the current maximum depth setting: 8
 -> Selector matches an ignored target, for example:

    Person person = Instancio.of(Person.class)
        .ignore(all(Phone.class))
        .set(field(Phone::getNumber), "555-66-77") // unused!
        .create();

 -> Selector targets a field or class in an object that was provided by:
    -> set(TargetSelector, Object)
    -> supply(TargetSelector, Supplier)

    // Example
    Supplier<Address> addressSupplier = () -> new Address(...);
    Person person = Instancio.of(Person.class)
        .supply(all(Address.class), () -> addressSupplier)
        .set(field(Address::getCity), "London") // unused!
        .create();

    Instancio does not modify instances provided by a Supplier,
    therefore, field(Address::getCity) will trigger unused selector error.

To resolve this error:

 -> Remove the selector(s) causing the error, if applicable.
 -> Suppress the error by enabling 'lenient()' mode:

    Example example = Instancio.of(Example.class)
        .lenient()
        .create();

    // Or via Settings
    Settings settings = Settings.create()
        .set(Keys.MODE, Mode.LENIENT);

    Example example = Instancio.of(Example.class)
        .withSettings(settings)
        .create();

For more information see: https://www.instancio.org/user-guide/#selector-strictness

	at org.instancio.internal.context.UnusedSelectorReporter.report(UnusedSelectorReporter.java:112)
	at org.instancio.internal.context.ModelContext.reportUnusedSelectorWarnings(ModelContext.java:162)
	at org.instancio.internal.context.ModelContext.reportWarnings(ModelContext.java:141)
	at org.instancio.internal.InstancioEngine.lambda$createRootObject$0(InstancioEngine.java:99)
	at org.instancio.internal.util.ExceptionHandler.conditionalFailOnError(ExceptionHandler.java:42)
	at org.instancio.internal.InstancioEngine.createRootObject(InstancioEngine.java:95)
	at org.instancio.internal.ApiImpl.create(ApiImpl.java:169)
	at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:45)`

**Additional information**
I enable trace logging for `org.instancio` and compare the logs for the raw test and the execution within the Spring application. 
There are differences: see the attached screenshot:
<img width="1448" alt="Bildschirmfoto 2023-06-13 um 21 52 19" src="https://github.com/instancio/instancio/assets/969608/eca33161-bad3-4913-be3b-270d9281edf1">

**Sample code reproducing the issue**
```java
@Data
public class Pruefauftrag {

    private Integer id;
    private Integer nummer;
    private LocalDate createdAt;
    private String createdBy;
    private LocalDate modifiedAt;
    private String modifiedBy;
}

return Instancio.ofList(Pruefauftrag.class)
            .size(10)
            .generate(field(Pruefauftrag::getId), gen -> gen.ints().range(1,100))
            .generate(field(Pruefauftrag::getNummer), gen -> gen.ints().range(1,100))
            .set(field(Pruefauftrag::getCreatedAt), LocalDate.now())
            .set(field(Pruefauftrag::getCreatedBy), "XYZ")
            .generate(field(Pruefauftrag::getModifiedAt), gen -> gen.temporal().localDate().past())
            .generate(field(Pruefauftrag::getModifiedBy), gen -> gen.text().loremIpsum())
            .create();
```

- Instancio version: 2.16.0

**Comment by armandino** [comment] 2023-06-14 04:50
@dominik42 thanks for reporting this issue. In the second log in the screenshot, it's using generators based on selectors. However, in the first log, it uses built-in generators. I'm not sure what could be the cause of this though.

Are you using Instancio under `src/main/test`? Could you also confirm the Java version and whether you are using JPMS or OSGi?

In addition, can you try:

- adding `System.setProperty("instancio.failOnError", "true")` before invoking Instancio
- and `lenient()` to suppress the unused selectors error

With the above we might see an exception that will hopefully shed more light on this.

**Comment by dominik42** [comment] 2023-06-15 04:27
Thanks @armandino for your response.
1) When it succeeds, it is used from a test class within src/main/test but when it failed, it is used from a normal Spring Service in src/main/java.
2) The addition of `System.setProperty("instancio.failOnError", "true")` did not change anything. The same exception with this large hint is printed. But I'm not sure, that the code line evaluate this properly is executed, see the attached screenshot, line 46 with is never reached.
<img width="759" alt="Bildschirmfoto 2023-06-15 um 06 16 39" src="https://github.com/instancio/instancio/assets/969608/1230b5b7-c660-4431-9af0-66137f2aa08e">

3) If i used lenient() all my customizations are gone and the generated items are not what I want, but yes, the error doesn't occur.

`org.instancio.exception.UnusedSelectorException:
Found unused selectors referenced in the following methods:

 -> Unused selectors in generate(), set(), or supply():
 1: field(Pruefauftrag, "createdAt")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:42)
 2: field(Pruefauftrag, "createdBy")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:43)
 3: field(Pruefauftrag, "id")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:40)
 4: field(Pruefauftrag, "modifiedAt")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:44)
 5: field(Pruefauftrag, "modifiedBy")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:45)
 6: field(Pruefauftrag, "nummer")
    at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:41)

This error aims to highlight potential problems and help maintain clean test code.

Possible causes:

 -> Selector did not match any field or class within this object.
 -> Selector target is beyond the current maximum depth setting: 8
 -> Selector matches an ignored target, for example:

    Person person = Instancio.of(Person.class)
        .ignore(all(Phone.class))
        .set(field(Phone::getNumber), "555-66-77") // unused!
        .create();

 -> Selector targets a field or class in an object that was provided by:
    -> set(TargetSelector, Object)
    -> supply(TargetSelector, Supplier)

    // Example
    Supplier<Address> addressSupplier = () -> new Address(...);
    Person person = Instancio.of(Person.class)
        .supply(all(Address.class), () -> addressSupplier)
        .set(field(Address::getCity), "London") // unused!
        .create();

    Instancio does not modify instances provided by a Supplier,
    therefore, field(Address::getCity) will trigger unused selector error.

To resolve this error:

 -> Remove the selector(s) causing the error, if applicable.
 -> Suppress the error by enabling 'lenient()' mode:

    Example example = Instancio.of(Example.class)
        .lenient()
        .create();

    // Or via Settings
    Settings settings = Settings.create()
        .set(Keys.MODE, Mode.LENIENT);

    Example example = Instancio.of(Example.class)
        .withSettings(settings)
        .create();

For more information see: https://www.instancio.org/user-guide/#selector-strictness

	at org.instancio.internal.context.UnusedSelectorReporter.report(UnusedSelectorReporter.java:112)
	at org.instancio.internal.context.ModelContext.reportUnusedSelectorWarnings(ModelContext.java:162)
	at org.instancio.internal.context.ModelContext.reportWarnings(ModelContext.java:141)
	at org.instancio.internal.InstancioEngine.lambda$createRootObject$0(InstancioEngine.java:99)
	at org.instancio.internal.util.ExceptionHandler.conditionalFailOnError(ExceptionHandler.java:42)
	at org.instancio.internal.InstancioEngine.createRootObject(InstancioEngine.java:95)
	at org.instancio.internal.ApiImpl.create(ApiImpl.java:169)
	at de.hub28.steel42.realisierung.pruefauftrag.PruefauftragService.dummyData(PruefauftragService.java:46)`

**Comment by armandino** [comment] 2023-06-15 06:19
@dominik42 hard to say what's going on. I was expecting to see an exception with `instancio.failOnError` enabled, but looks like there is none.

Any chance you could provide a reproducible sample? I created a Spring service to try it out  and it's working on my end:

![image](https://github.com/instancio/instancio/assets/1159054/f6415cb5-893d-45f1-8278-3fccca191f33)

**Comment by dominik42** [comment] 2023-06-15 08:36
I've prepared an example :-) This is a simple Vaadin app created with  start.vaadin.com. 
Unpack, start the app by `mvn spring-boot:run` and then browse to `http://localhost:8080`. 
Click the menu item `Grid with filters`, the grid should be shown with data from the default InMemory H2 DB instance.
If all is setup properly, go into `src/main/java/com/example/application/views/gridwithfilters/GridwithFilterView.java`
In line 239 you find the method using Instancio. Comment the line 235-237 above and uncomment line 239. Restart the app (maybe your IDE auto-restart the app). If you click the menu item mentions above again, the error occur.
Hope, that helps and you can reproduce this weired behaviour.

[my-app.zip](https://github.com/instancio/instancio/files/11754931/my-app.zip)

**Comment by armandino** [comment] 2023-06-16 05:41
@dominik42 thank you for providing the sample! It was very helpful in getting to the root cause.

The problem was that a selector, such as `field(Pojo::getValue)` was resolving the class from the method reference using `Class.forName(className)`. When running the application under production code, the POJO class was being loaded by a different classloader. As a result, there were two different instances of `Pojo.class` that are not equal each other. This, in turn, caused hash map look-ups to fail resulting in unused selector error.

I just pushed a fix to Maven central which should resolve this issue. Please try version `2.16.1`.

**Closed** 2023-06-17 05:53 UTC
Labels: type: bug, component: core

**Comment by dominik42** [comment] 2023-06-18 15:11
Bugfix confirmed, works now as expected.
Thanks for the fast response and solution.
