### ISSUE TITLE
Support for Kotlin sealed class types

### ISSUE THREAD

**Issue by lukaszkalnik** [instancio/instancio#614] opened 2023-05-23 08:10 UTC
I have following data types defined in Kotlin:

# ProtectionDevice.kt
```
sealed class ProtectionDevice
object None : ProtectionDevice()
```
Then I have a Java class, which references the `sealed class` type:

# ProductDetail.java
```
class ProductDetail {
    private final ProtectionDevice protectionDevice;
}
```

However, when I do `Instancio.create(ProductDetail::class.java)` (in Kotlin), the `protectionDevice` field in the generated instance is null. 
I can however set it explicitly by doing
```
Instancio.of(ProductDetail::class.java)
    .set(field(ProductDetail::getProtectionDevice), ProtectionDevice.None)
    .create()
```

**Comment by armandino** [comment] 2023-05-23 19:36
@lukaszkalnik, thanks for raising the issue and providing an example!

I was able to reproduce the issue using your example. The root cause is that a `sealed` class is considered to be an abstract type. Since Instancio doesn't automatically resolve implementations for abstract types, the result is `null`.

The workaround is to either `set()` the field, as you suggested, or use `subtype()` to specify the implementation class. If the sealed class and its implementation have properties that need to be populated, then `subtype()` should do that for you.

Using slightly modified versions of your sample classes:

```kotlin
sealed class ProtectionDevice {
    abstract val foo: String
}

data class Widget(override val foo: String, val bar: String) : ProtectionDevice()

class ProductDetail {
    val protectionDevice: ProtectionDevice? = null
}

val result = Instancio.of(ProductDetail::class.java)
    .subtype(all(ProtectionDevice::class.java), Widget::class.java)
    .create()

// Sample output: ProductDetail(protectionDevice=Widget(foo=YVORVXFFDK, bar=HYRAZV))
```

It's possible to automatically resolve implementations if you have many sealed classes. Below are a couple of sample projects if you want to go down this route:

- Using `InstancioServiceProvider` SPI
  https://github.com/instancio/instancio-samples/tree/main/type-resolver-sample

- Using Jandex to map subtypes via `instancio.properties`
  https://github.com/dafriedmann/instancio-jandex-subtype-mapping

- Additional info: https://www.instancio.org/user-guide/#subtype-mapping

**Comment by armandino** [comment] 2023-05-31 05:19
@lukaszkalnik I'll close this issue as there're no changes to be made. If you have any other questions, please feel free to add a comment.

**Closed by armandino** 2023-05-31 05:19 UTC
Labels: status: works-as-designed
