### ISSUE TITLE
Temporal specs `past()` and `future()` generate different values for a given `@Seed`

### ISSUE THREAD

**Issue by temp-droid** [instancio/instancio#1105] opened 2024-07-16 05:40 UTC
**Describe the bug**
`Gen.temporal().localDate().past().get()` does not return the same date every day when seed is provided.

**Expected result**
Same LocalDate value/date should be returned every day if seed is present.

**Actual result**
Every day a new LocalDate is generated.

Example with a test passing yesterday but failing today:
```
Expected :2001-05-19 (java.time.LocalDate)
Actual   :2003-10-20 (java.time.LocalDate)
```

**Additional information**
Tests do not fail on the same day. Only failing after the next day.

Other generators that I use (string, int) do not have that issue.

`Gen.temporal().date().past()` did not seem impacted in my tests.

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
    @Seed(1)
    @Test
    void should_generate_same_past_local_date_every_day_using_Gen() {
        LocalDate pastDate = Gen.temporal().localDate().past().get();

        assertThat(pastDate).isEqualTo(LocalDate.of(2003, 10, 20)); // passing today 2024-07-16
    }
```
If you are not running this test today, you need to adapt the assertion to pass the test and wait one day to rerun the test to see it fail.

https://github.com/temp-droid/instancio-local-date-bug/blob/master/src/test/java/InstancioTemporalTest.java

- Java version: 17
- Instancio version: 4.8.1

**Comment by armandino** [comment] 2024-07-16 21:22
Hi @temp-droid, thank you for reporting this issue and the sample project. It seems both, `past()` and `future()` methods are prone to this issue as they are all using `now()` as the reference point. For example, a `future()` date, even if it happens to be next year, will become a past date. I'm not sure what would be a good fix for this since the reference point is always changing. 

I think the best way forward is to document this behaviour, and for cases where the dates must be truly fixed, to specify an explicit min/max value, e.g.

```java
temporal().localDate().range(SOME_MIN, SOME_MAX)
```

What do you think?

**Comment by temp-droid** [comment] 2024-07-17 05:52
For `.past()` we could have a look at what `InstantGenerator` is doing because I cannot reproduce the issue with it while the range must change every second (`Instant.now().minusSeconds(1)`).

```java
    @Seed(1)
    @Test
    void test_past_instant() {
        Instant pastInstant = Gen.temporal().instant().past().get();

        assertThat(pastInstant.toEpochMilli()).isEqualTo(1569548985215L);
    }
```
Could this work?
```java
    @Seed(1)
    @Test
    void test_past_local_date_using_instant() {
        Instant pastInstant = Gen.temporal().instant().past().get();

        LocalDate localDate = pastInstant.atZone(ZoneId.systemDefault()).toLocalDate();

        assertThat(localDate).isEqualTo(LocalDate.of(2019, 9, 27));
    }
```
and in `LocalDateGenerator` you could rely on `Instant.now().minus(1, ChronoUnit.DAYS);`. Even if it is not clear to me how it would make a difference in the range.

For  `.future()` it will indeed be more tricky since no date will be future proof, except maybe if you stay close to the hardcoded max. But that would reduce a lot the amount of possible values.

Your proposal sounds good as a documented workaround, it sounds fair that there is no perfect solution for future dates.

**Comment by temp-droid** [comment] 2024-07-18 07:44
Hello @armandino ,

I can confirm that this test pass 2 days in a row:
```java
    @Seed(1)
    @Test
    void test_past_local_date_using_instant() {
        Instant pastInstant = Gen.temporal().instant().past().get();

        LocalDate localDate = pastInstant.atZone(ZoneId.systemDefault()).toLocalDate();

        assertThat(localDate).isEqualTo(LocalDate.of(2019, 9, 27));
    }
```
I did not have time to investigate why yet, but you might have a better idea how it works internally and how to adapt the LocalDateGenerator?

**Comment by armandino** [comment] 2024-07-18 18:03
Hey @temp-droid, thanks a lot for the additional info. Based on your investigation, I looked into the `Instant` generator and found that this behaviour is actually due to a bug in the random generator implementation from `org.apache.commons:commons-math3` that Instancio uses under the hood. There seems to be a problem with certain ranges that produce the same result. I submitted a bug report for this:

- https://issues.apache.org/jira/browse/MATH-1668
- Reproducer: https://github.com/armandino/commons-math3-bug

If this gets fixed, the `past()` method for `Instant` will have the same problem as `LocalDate` and other temporals. I think based on this, the best way forward is still https://github.com/instancio/instancio/issues/1105#issuecomment-2231849306

**Closed** 2024-07-19 16:00 UTC
Labels: type: bug, component: core
