### ISSUE TITLE
Static initializer

### ISSUE THREAD

**Issue by alabotski** [instancio/instancio#430] opened 2023-02-15 16:26 UTC
Does [instancio](https://github.com/instancio/instancio) support lcaess with static initlizer?
For example

```
class Address {
private String name;
private Address (){}
public static Address  of(){
return new Address(); 
}

class Address2 {
private String name;
private Address (String name){this.name=name;}
public static Address  of(String name){
return new Address(name); 
}

class Person {
private Address address;
private Address2 address2;
private Person(){}
public static of() {
return new Person();
}
```

I have a dependency with such classes, So I cannot change their structure
I tried to generate data with instancio
But as a result, I have a lot of warnings and an error
The library does not support the work, or did I do something wrong? =(

**Comment by alabotski** [comment] 2023-02-16 05:13
I added small example
[Static_initializer.patch](https://github.com/instancio/instancio/files/10752392/Static_initializer.patch)

**Comment by armandino** [comment] 2023-02-16 05:42
@alabotski, thank you for the sample. The error was caused by attempting to set a `String` field to a `Supplier`. If you make a small change to the sample, it will resolve the error:

```java
Library library = Instancio.of(Library.class)
        .set(field(BookType1::getCaption), "Test book of type 1")
        .set(field(BookType2::getCaption), "Test book of type 2")
        .set(field(Library::getAuthor), "Author")
        .create();
```

With strings, it's better to use `set()` as above, but if you prefer to use `supply()` instead, you can use this version:

```java
Library library = Instancio.of(Library.class)
        .supply(field(BookType1::getCaption), () -> "Test book of type 1")
        .supply(field(BookType2::getCaption), () -> "Test book of type 2")
        .set(field(Library::getAuthor), "Author")
        .create();
```

**Comment by alabotski** [comment] 2023-02-16 06:03
Thanks it's my mistake

**Comment by armandino** [comment] 2023-02-16 06:20
@alabotski, any time! No worries :)

I will close this issue. Let me know if you have any other questions.

**Closed by armandino** 2023-02-16 06:20 UTC
Labels: type: enhancement
