### ISSUE TITLE
Cannot generate value of type that is subtype of field class

### ISSUE THREAD

**Issue by Yuksovich** [instancio/instancio#446] opened 2023-02-20 09:51 UTC
**Describe the bug**
String generator cannot generate value for field of type java.lang.Object 

**Expected result**
String value assigned to Object field

**Actual result**
org.instancio.exception.InstancioApiException: 
Generator type mismatch:
Method 'string()' cannot be used for type: java.lang.Object

**Additional information**
It seems that this trouble is caused by incorrect usage of method `Class.isAssignableFrom` in `GeneratorSupport.supports`:
```java
final Class<?> typeArg = TypeUtils.getGenericSuperclassTypeArgument(generator.getClass());
if (typeArg != null) {
    return typeArg.isAssignableFrom(type)
        || PrimitiveWrapperBiLookup.findEquivalent(typeArg)
        .filter(type::isAssignableFrom)
        .isPresent();
}
```
from method documentation of `isAssignableFrom`:

<i>Determines if the class or interface represented by this Class object is either the same as, or is a superclass or superinterface of, the class or interface represented by the specified Class parameter. </i>

so it seems that it should be `type.isAssignableFrom(typeArg)` since the typeArg is assigned to type.

**Sample code reproducing the issue**
```java
Instancio.of(Request.class)
            .generate(field("objectValue"), Generators::string)
            .create();
```

- Instancio version: 2.9.0

**Comment by armandino** [comment] 2023-02-20 18:04
@Yuksovich, thank you for reporting this bug and finding the root cause. Much appreciated!

The fix will be available in `2.10.0`.

**Comment by armandino** [comment] 2023-02-20 22:32
@Yuksovich `2.10.0` should be available now from Maven central.

**Comment by armandino** [comment] 2023-02-23 06:06
@Yuksovich I will close this issue. Feel free to re-open if you're still having problems. Thanks again for the bug report.

**Closed by armandino** 2023-02-23 06:06 UTC
Labels: type: bug
