### ISSUE TITLE
Cannot implement custom generator for ImmutableMap

### ISSUE THREAD

**Issue by AndrMoiseev** [instancio/instancio#524] opened 2023-03-27 07:54 UTC
**Describe the bug**
I'm trying to implement custom generators for Guava immutable collections. For ImmutableList and ImmutableSet all works like a charm. But for ImmutableMap my generator generates correct instance of ImmitableMap, but later in Instancio code map.putAll called which leads to Exception. I explicitly defined Hint - Hints.afterGenerate(AfterGenerate.DO_NOT_MODIFY), but it not helped. 

**Expected result**
Suppose you have following class:
```
@Value
private static class ValueWithImmutableMap {
    ImmutableMap<String, String> valueMap;
}
```
and following test:
```
@Test
public void canGenerateValueWithImmutableMap() {
    // Arrange, Act
    var result = Instancio.create(ValueWithImmutableMap.class);

    // Assert
    assertNotNull(result);
    assertNotNull(result.getValueMap());
}
```
Test should pass if correct generator implemented for ImmutableMap.

**Actual result**
Test fails on first assertion.

**Additional information**
The problem line of code is InstancioEngine.java:288

- Instancio version: 2.12.0

**Comment by armandino** [comment] 2023-03-28 05:09
@AndrMoiseev I added a comment in #525. Since this is not supported right now, I will close this bug and keep #525 to track this issue.

**Comment by AndrMoiseev** [comment] 2023-03-28 05:45
@armandino actually I was able to implement the generator. See the code below.
The only problem is internal implementation that still tries to modify the output of custom generator.

```
@RequiredArgsConstructor
 class ImmutableMapGenerator implements Generator<ImmutableMap> {

        private final ServiceProviderContext context;
        private final Class keyType;
        private final Class valueType;

        @Override
        public ImmutableMap generate(Random random) {

            var map = Instancio.of(Map.class)
                    .withTypeParameters(keyType, valueType)
                    .withSeed(random.getSeed())
                    .withSettings(context.getSettings())
                    .create();
            return ImmutableMap.copyOf(map);
        }

        @Override
        public Hints hints() {
            return Hints.afterGenerate(AfterGenerate.DO_NOT_MODIFY);
        }
    }
```

**Comment by armandino** [comment] 2023-03-28 05:53
@AndrMoiseev could you provide a minimal sample that reproduces the issue?

**Comment by armandino** [comment] 2023-03-28 06:24
@AndrMoiseev I was able to reproduce the issue. This will be fixed in the next release.

**Comment by armandino** [comment] 2023-03-29 03:30
@AndrMoiseev, please try `2.12.1`. It should be available from Maven central shortly.

**Closed** 2023-03-29 03:30 UTC
Labels: type: bug

**Comment by AndrMoiseev** [comment] 2023-03-29 06:16
@armandino works like a charm, thank you!

Great product by the way. Came from EasyRandom and extensibility is the main selling point for me.

**Comment by armandino** [comment] 2023-03-29 06:49
@AndrMoiseev thank you for the feedback! Much appreciated.
